[General]
Name=ControllerOS Xbox Controller
ControllerMode=le
DiscoverableTimeout=0
PairableTimeout=0

[LE]
MinConnectionInterval=7
MaxConnectionInterval=9
ConnectionLatency=0
ConnectionSupervisionTimeout=600
